export const OrderTypes = {
  ADD_TIP: 'ADD_TIP',
  ADD_TAX: 'ADD_TAX',
  ADD_PRODUCT_TO_ORDER: 'ADD_PRODUCT_TO_ORDER',
  REMOVE_PRODUCT_FROM_ORDER: 'REMOVE_PRODUCT_FROM_ORDER',
  SET_ORDER_STATUS: 'SET_ORDER_STATUS',
  CART_LOADED: 'CART_LOADED',
  CART_CREATED: 'CART_CREATED'
};
