export const UserTypes = {
  USER_LOADED: 'USER_LOADED',
  USER_REQUESTED: 'USER_REQUESTED',
  USER_LOGIN: 'USER_LOGIN',
  REGISTER_USER: 'REGISTER_USER',
  VALIDATE_TOKEN: 'VALIDATE_TOKEN',
  PROFILE_LOADED: 'PROFILE_LOADED',
};
